language: node_js
node_js:
- '8'
cache: yarn
branches:
  only:
  - develop
before_install:
- cat /dev/null > .yarnrc
script: yarn run ng build --target=production --aot
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: "./dist"
  on:
    branch: develop
  target_branch: master
  github_token:
    secure: "YX4fT6oaJUiDmEnJ12TqBMulso82IEkAv5i6JjlZpomzwFkyWjdekDBnGhZsgxR3rufGLDFlw9Tny1+u/YMtuDuJBUQ/0whdQdzLbY0eB+aeyejqBuuqGkKu9esMgg2p2Srj1QKWuVWQIw+Ev6V6mf0HBdBMcNzZu/sGP0QS5blab9wlb6g0aLvk+VH9GjoLQKuBC/lUirjiv5+iguy0Vuk12SqUBIHz4GZoOzRu9ivorfjgctW1MlxqBtWQEut9CbT7qWxp4zut1UuNB8+rc48u9bN3i5Cfz5ub9oAF29CVyxB0lpvK5UAkHZ6De0dczo7Rc1i8//BOOni/5Zj59Bz2+PTQ7HUYUoo91Ha+syhRUZlL9adYt4H4F+ElqurNT8eBn3vV6GdexXo0wiJTdBZhXHC3vM5yUWCsFBI9LWs4WDDdQj1pEe1sTLVharURDm1XRswk6bwV+TrNNgX/9cnYV6pZwQA1d/LJ7nduyMvhJutdouN7Z6VrZKdhUqZMeqc++KRT6qMcpw+B3b0jEruAL2d+gbdQXXzih5L6U9wUkm5+nHFox1wn+026YUE4XycGcHU+0f+iCBSFCOKGp6TXGnixFO9qqDRLWOHfUKWr6pT653ZNZ9RUsE491D0Satcz3I04g7NLzw5837i8pHGnAghSMin6UYrSIVypz8w="