language: node_js
node_js:
- '8'
cache: yarn
branches:
  only:
  - develop
before_install:
- cat /dev/null > .yarnrc
script: yarn run ng build --target=production --aot
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: "./dist"
  on:
    branch: develop
  target_branch: master
  github_token:
    secure: P5Xt2JUsDe8s9oOkF+H8eNo0+nmUO/sLAaKY6dDhvdmVJiUV5qDKJ38bKoKKCNb7gb6k2X+0LRUs1vpkvPXyienWGqd73kOB3sBBxwoKcaUc4L66IBKqFklFf6nBwKr94Gac3bv/A5c7TQRdqS5bn2a3uAve5l2J/8lQ+jQsBWoci6KRp3v2Y/212xiBpmF2Y1r5UwesllhCZFJWkYgvy3otd6n9KQlz+c+phgOqgFzH7A9J89kAgU1zvH4dOmq7HZIm7pVHCpjUYnoqLQpY3jif9nC51imppjNuNaY6/44XFDrl3IPvaa2Xq2fxQR94O+Xs7F76338rGvgYRIgm3qQ4IXebl1SqH438hma4CRkkTllAXM7OologdAqkPDWy64U+HRqm33hFJ6TEYjgnd1F9RLCkJZOA1/TTdhtG7HiUz7kPXHjd7m5YP2gJZrcddIRdjxuYsP6CHalDw8CV3GCSHWraFzi4mFUXFY/XrBwZMQt8WWCi3LHKEj7+8S+dnu2uUSYVLd1J094uv2T/Qg5SnGIVu1c6SpSGdgkj7lxb9o5TnYA3M4bmxRqWci+kB3On5cbeZDbxsFk15OOdm2BD/ici1PFD5iwZiSd8eKYOe0BTGl+SrP7OQCZaFMKfRgJA9oFv+rIKdEQTBj2cTnaTscjKs6BgQ+GTNPHc3Z0=
env:
  secure: UCB5x99qFZJ8eubn5T3MjjvGSxtf398o9jeK/G7JBjqZgHsy7HAxA1DCkCDcd/2CyATQqVGFcVajqy/OBelm3AFVvpzmStDQlvnRboHo/g8LniPIO79mVCkx1gngkEuXrJ/+xgNYCldPukKzJQ5Iu0dJJ4dAiQC68Awk8H0WZ6gyvOUtjDcgQ3/MXQfoQsFziOrzJYpxtBfhaGYlIweJxVsK+RvGBjh0ZyJfxwpy8sQNBZtnx+WWVO6LnLFbL81ayaj3aLe/H+3UnZ5uvqlfRrWRIYWicghK52hr3CMmyObvNuEK/WDOAGDWNqxu8gk2JZ4EU6K78yuwc0NfFefwm1Xi2sWvSzrUTlBpfgOEWAUwYoxMWoG/sfbkEXHEEI0enXB9CY4ED0TymGItLxLs/Rjxe39hqdJJJ/HPKtb20Qm/QZsALOUkGx48PoB3VT4uqRcE9gduweTFJsM8JeUMySHFK+/3ZcOlGLVMRCedzYV5UxpPACQPWVQQCtjG9Es8zkdDQ3ZaGaDJA5e+lBQKyYNxJiyY+DxCwf4bh/+CcELbPMIDfJbdXPP0Ooj5wSGWURi42km2AlE7lLz7FmzOFZhkhzzjwP1v3abcztH55RuXlQKcbqdt19WDggkAzy9cbK1Ynywc8dqkoSma3xRNAqCFhW1vQ+h3amg1TwFMYTQ=
