language: node_js
node_js:
- '8'
cache: yarn
branches:
  only:
  - develop
before_install:
- cat /dev/null > .yarnrc
script: yarn run ng build --target=production --aot
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: "./dist"
  on:
    branch: develop
  target_branch: master
  github_token: "$GITHUB_TOKEN"
env:
  secure: BGn89gHsuKDxPOpWSlGCbBIMlL9tjZKIwuvccdUrOY308RhxPQzHftMkvLaw3Da/69m3qDWuxjCf+ea59DQwwCw5ySDOn7ClCbVHHsy31+pGRXi0mB/2tcsoZm9dBEGjnPEAxM+s+Rn3i25EMQyjigbGfzq5xZoSafeRBeApBGx4uf5omkLOuqwm0dX2Xj5OhTuweEsdrctI6cNuLAXmRM3oZti8kLjY4XylpUGEJYZaTnqSPoHX21i5UqMENml7v2DyAdJYE7B/1QHzylZaut1fKyZZhcnFTFvYT1YGCrDdWNGYKP66pCJ+RnAp5z0MX1W8NoBScxLWnobCP0L3sVq//9E5DVmA6vJsQ8UzyaFXad1Poh6I8erwNToLN0L+05UDuZdm5mq4TOpuVKl6OQelgg93xAtx+6c/yOtL6QhO0QCH0LYIEzfapDpwcmdUEg1/x7TSNo2Qst2CTzuKgWqeFcjN0n08cK5MgWOVc37gDvz9VsO6Y+qSleWo/oZzopf+hmXkqOX9kbDfrT/JFLDRjvd0fMxhzeCwtxwdfVlfgHnWtPNr7EmaEV2daKVs85b0YlJhfgawBMaUwIj4kB7Ig63Fve5TYT6eWgtObZEp9LCRkDre8lkDGqxdCsS8lOxsWslT324sxS/DWnss6lZyFEfI9rvokk8O8GQ5t0I=
